Update audits to handle limited ads serving
googleads/publisher-ads-lighthouse-plugin pull request #237
Opened 2020-10-28 14:21 UTC by warrengm

Update audits and docs to handle limited ads: https://developers.google.com/doubleclick-gpt/guides/general-best-practices

Notably this tweeks the `loads-gpt-from-sgdn` audit to be a `loads-gpt-from-official-source`. I left the old docs behind, but we should delete it after launching this audit to our server.

2020-10-28 14:35 UTC, jburger424 approved these changes

2020-10-28 14:35 UTC, jburger424 commented on lighthouse-plugin-publisher-ads/test/smoke/expectations/limited-ads-dynamic-loading.js
> +// Copyright 2019 Google LLC
s/19/20, below too

2020-10-29 09:09 UTC, jimper requested changes

2020-10-29 09:09 UTC, jimper commented on docs/audits/loads-gpt-from-official-source.md
> +integrations could use
Standard integrations should use:

2020-10-29 09:09 UTC, jimper commented on docs/audits/loads-gpt-from-official-source.md
> +And integrations with limited ads could use:
Integrations that request [limited ads](https://support.google.com/admanager/answer/9882911) should use:

2020-10-29 09:09 UTC, jimper commented on lighthouse-plugin-publisher-ads/messages/en-US.json
> +    "message": "Load GPT from 'securepubads.g.doubleclick.net' for standard integrations from 'pagead2.googlesyndication.com' for limited ads. [Learn more](https://developers.google.com/publisher-ads
or

2020-11-04 07:16 UTC, jimper requested changes

2020-11-04 07:16 UTC, jimper commented on lighthouse-plugin-publisher-ads/messages/en-US.json
> +    "message": "Load GPT from 'securepubads.g.doubleclick.net' for standard integrationsor from 'pagead2.googlesyndication.com' for limited ads. [Learn more](https://developers.google.com/publisher-a
integrations or

2020-11-04 07:16 UTC, jimper commented on lighthouse-plugin-publisher-ads/audits/loads-gpt-from-official-source.js
> +  'Load GPT from \'securepubads.g.doubleclick.net\' for standard integrations' +
missing space after

2020-11-04 07:16 UTC, jimper commented on docs/audits/loads-gpt-from-official-source.md
> +Integrations with limited ads should use:
Make "limited ads" a link to https://support.google.com/admanager/answer/9882911

2020-11-04 23:21 UTC, mmisim approved these changes

2020-11-04 23:21 UTC, mmisim commented on docs/audits/loads-gpt-from-official-source.md
> +should use:
```suggestion
Ensure that GPT is being loaded from an official source.  For standard integrations,
use:
```

2020-11-04 23:21 UTC, mmisim commented on docs/audits/loads-gpt-from-official-source.md
> +Integrations with limited ads should use:
```suggestion
For integrations with limited ads, use:
```

2020-11-06 00:42 UTC, jimper approved these changes

2020-11-10 03:04 UTC, merged