Adding audits for deprecated api and general error catching
googleads/publisher-ads-lighthouse-plugin pull request #252
Opened 2021-01-07 20:50 UTC by avparmar

2021-01-07 20:50 UTC, avparmar commented
I'm adding the docs too, just wanted these up for review meanwhile.

2021-01-08 19:16 UTC, warrengm commented
Implementation LGTM. We will probably discuss scoring when you add `plugin.js`.

For testing, can we create some smoke tests?

2021-01-11 16:37 UTC, warrengm requested changes

2021-01-11 16:38 UTC, warrengm commented
Ooops! Sorry! I had my comments stuck as draft. Posted them now

2021-01-11 18:28 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +        .filter((item) => item.text.toLowerCase().includes('deprecated'))
Added the condition.

2021-01-12 20:33 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +        .filter((item) => item.text.toLowerCase().includes('deprecated'))
To clarify, added both cases in since we use both words in console messages.

2021-01-12 20:33 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +          .sort((a, b) => (a.description || '').localeCompare(b.description || ''));
Changed the sorting rule to the timestamp field.

2021-01-12 20:34 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
> +        item.source === 'exception' ||
Done.

2021-01-12 20:34 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
> +        .filter((item) => item.url && isGpt(item.url))
Done.

2021-01-12 20:34 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +  failureTitle: 'Reduce deprecated GPT API usage',
Applied.

2021-01-12 20:35 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +  description: 'Measures occurences of deprecated GPT API usage based on log messages. ' +
Updated these for both audits based on the standards.

2021-01-12 20:35 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
> +  title: 'GPT Errors and Exceptions',
Done.

2021-01-12 20:35 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
> +  failureTitle: 'Reduce deprecated GPT API errors and exceptions',
Applied.

2021-01-12 20:36 UTC, avparmar commented on lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
> +  static filterAccordingToOptions(items, options) {
Agreed. Removed it and other code pertaining to options which we aren't using.

2021-01-19 22:48 UTC, warrengm approved these changes

2021-01-20 00:53 UTC, merged